apiVersion: apps/v1
kind: Deployment
metadata:
  name: nta-kube-db
  labels:
    app: nta-kube-db
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nta-kube-db
  template:
    metadata:
      labels:
        app: nta-kube-db
    spec:
      containers:
      - name: db
        image: postgres:15-alpine
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: db
          - name: POSTGRES_PASSWORD
            value: db
          - name: POSTGRES_DB
            value: api
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc
