apiVersion: apps/v1
kind: Deployment
metadata:
  name: nta-kube-api
  labels:
    app: nta-kube-api
  namespace: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nta-kube-api
  template:
    metadata:
      labels:
        app: nta-kube-api
    spec:
      containers:
      - name: api
        image: ghcr.io/do3-2023/nta-kube/api:main
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: db_url
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: db_name
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-secret
                key: password
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
