apiVersion: apps/v1
kind: Deployment
metadata:
  name: nta-kube-webapp
  labels:
    app: nta-kube-webapp
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nta-kube-webapp
  template:
    metadata:
      labels:
        app: nta-kube-webapp
    spec:
      containers:
      - name: webapp
        image: ghcr.io/do3-2023/nta-kube/webapp:main
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
        env:
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: webapp-config
                key: api_url
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
